# Generated by Django 5.0.5 on 2024-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
                ('senha', models.CharField(max_length=128)),
                ('confirma_senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
