# Generated by Django 5.1.1 on 2024-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastro_registro",
            "0003_rename_confirma_senha_cadastroregistro_confirma_senha_paciente_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastroregistro",
            name="confirma_senha_paciente",
        ),
        migrations.AlterField(
            model_name="cadastroregistro",
            name="cpf_paciente",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="cadastroregistro",
            name="email_paciente",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="cadastroregistro",
            name="senha_paciente",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cadastroregistro",
            name="sexo_paciente",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                max_length=1,
            ),
        ),
    ]
